services:
  postgres:
    image: postgres:12.9
    container_name: postgres
    environment:
      - POSTGRES_USER=spaetirun
      - POSTGRES_PASSWORD=spaetirun
      - POSTGRES_DB=spaetirun
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
